<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#practice:" data-toc-modified-id="practice:-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>practice:</a></span></li></ul></div>

# practice:
한국 주가 데이터로 등락률을 기준으로(상당히 극단적...) 회사를 나누어보자. 기준은 2022-11-30 이다. 
출처 : https://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201040101

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_ko_221130 = pd.read_csv('/Users/Angela/Desktop/Personal/StockData/krx_20221130.csv', encoding = 'cp949')
df = df_ko_221130[df_ko_221130['시장구분'] == 'KOSPI'][['종목코드', '종목명', '종가', '등락률', '거래량', '거래대금', '시가총액', '상장주식수']]
df

,종목코드,종목명,종가,등락률,거래량,거래대금,시가총액,상장주식수
1,095570,AJ네트웍스,6110,0.49,110183,674688330,286084222450,46822295
2,006840,AK홀딩스,15150,2.02,14692,221418900,200700549150,13247561
6,027410,BGF,4365,18.29,11158585,49369104315,417803792715,95716791
7,282330,BGF리테일,205500,3.27,215574,44268140500,3551842683000,17283906
9,138930,BNK금융지주,7390,1.23,1801684,13323873630,2408661467940,325935246
...,...,...,...,...,...,...,...,...
2665,005010,휴스틸,5420,-1.45,439253,2383570150,212399366500,39188075
2673,000540,흥국화재,3165,-0.94,85333,269593750,203327971425,64242645
2674,000547,흥국화재2우B,19300,-0.26,76,1470100,2964480000,153600
2675,000545,흥국화재우,6020,0.67,910,5490510,4623360000,768000
2676,003280,흥아해운,1625,-0.91,426373,691332165,390690460875,240424899

In [4]:
rate_bins = [-30, -20, -10, -5, -2, 0, 2, 5, 10, 20, 30]
letter_grades = ['절망', '통곡', '눈물', '불안', '설마', '안심', '미소', '행복', '입틀막', '풀매도']

In [5]:
cate_rate = pd.cut(x = df.등락률, bins = rate_bins, labels = letter_grades)
df['심리상태'] = cate_rate
df

,종목코드,종목명,종가,등락률,거래량,거래대금,시가총액,상장주식수,심리상태
1,095570,AJ네트웍스,6110,0.49,110183,674688330,286084222450,46822295,안심
2,006840,AK홀딩스,15150,2.02,14692,221418900,200700549150,13247561,미소
6,027410,BGF,4365,18.29,11158585,49369104315,417803792715,95716791,입틀막
7,282330,BGF리테일,205500,3.27,215574,44268140500,3551842683000,17283906,미소
9,138930,BNK금융지주,7390,1.23,1801684,13323873630,2408661467940,325935246,안심
...,...,...,...,...,...,...,...,...,...
2665,005010,휴스틸,5420,-1.45,439253,2383570150,212399366500,39188075,설마
2673,000540,흥국화재,3165,-0.94,85333,269593750,203327971425,64242645,설마
2674,000547,흥국화재2우B,19300,-0.26,76,1470100,2964480000,153600,설마
2675,000545,흥국화재우,6020,0.67,910,5490510,4623360000,768000,안심
2676,003280,흥아해운,1625,-0.91,426373,691332165,390690460875,240424899,설마

In [7]:
cate_rate

1        안심
2        미소
6       입틀막
7        미소
9        안심
       ...
2665     설마
2673     설마
2674     설마
2675     안심
2676     설마
Name: 등락률, Length: 942, dtype: category
Categories (10, object): ['절망' < '통곡' < '눈물' < '불안' ... '미소' < '행복' < '입틀막' < '풀매도']

오늘 사람들이 얼마나 울고 웃었는지 보자.

In [8]:
df['심리상태'].value_counts()

안심     426
설마     273
미소     167
불안      34
행복      19
입틀막      9
눈물       8
풀매도      5
통곡       1
절망       0
Name: 심리상태, dtype: int64

극단적인 종목을 알아보자.

In [ ]:
# set option of ma
pd.set_option('display.max_rows', 50)

df.loc[(df['심리상태'] == '행복')|(df['심리상태'] == '입틀막')|(df['심리상태'] == '풀매도')][['종목명', '심리상태']].sort_values(by = '심리상태', ascending = False)

In [ ]:
df.loc[(df['심리상태'] == '절망')|(df['심리상태'] == '통곡')|(df['심리상태'] == '눈물')][['종목명', '심리상태']].sort_values(by = '심리상태', ascending = False)

종목 하나는 완전히 난리가 난 것 같다. 나쁜 의미에서...

~그만알아보자.~